    package View;

import Controller.EstadoCivilController;
import Dao.EstadoCivilDao;
import Dao.EstadoCivilImpl;
import Controller.FuncionarioController;
import Controller.TipodeIdentificacionController;
import Dao.FuncionarioDao;
import Dao.FuncionarioImpl;
import Dao.TipoIdentificacionDao;
import Dao.TipoIdentificacionImpl;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import Model.EstadoCivil;
import Model.Funcionario;
import Model.TipodeIdentificacion;
import Util.Mensajes;

import javax.swing.*;
import java.awt.event.MouseAdapter;



public class JFFPrincipal extends javax.swing.JFrame {

    private TipodeIdentificacionController tipoIdCtrl;
    private EstadoCivilController estadoCivilCtrl;
    private FuncionarioController funcionarioCtrl;
    /**
     * Creates new form JFFPrincipal
     */
    public JFFPrincipal() {
        initComponents();
        init();
    }
    
    private void init(){
        llenarComboTipoDocumento();
        llenarComboEstadoCivil(); 
        llenarTablaFuncionarios();
        completar();
        
        jBEliminar.setEnabled(false);
        jBEditar.setEnabled(false);
        

    }
    
    private void llenarComboTipoDocumento(){
        TipoIdentificacionDao tipoIdentificacionDao = new TipoIdentificacionImpl();
        tipoIdCtrl = new TipodeIdentificacionController(tipoIdentificacionDao);
        jCBTipoDocumento.setModel(tipoIdCtrl.llenarCombo());
    }
    
    private void llenarComboEstadoCivil(){
        EstadoCivilDao estadoCivilDao = new EstadoCivilImpl();
        estadoCivilCtrl = new EstadoCivilController(estadoCivilDao);
        JCBEstadoCivil.setModel(estadoCivilCtrl.llenarCombo());
    }
    
    private void llenarTablaFuncionarios(){
        FuncionarioDao funcionarioDao = new FuncionarioImpl();
        funcionarioCtrl = new FuncionarioController(funcionarioDao);
        jTblFuncionarios.setModel(funcionarioCtrl.llenarTabla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCBTipoDocumento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFDocumento = new javax.swing.JTextField();
        jBEditar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBRefrescar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblFuncionarios = new javax.swing.JTable();
        jBGuardar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        JDChFechaNac = new com.toedter.calendar.JDateChooser();
        jCBSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFFTelefono = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JCBEstadoCivil = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADireccion = new javax.swing.JTextArea();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jCBTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Tipo ID:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTION FUNCIONARIOS");

        jLabel3.setText("Documento:");

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBRefrescar.setText("Refrescar");
        jBRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefrescarActionPerformed(evt);
            }
        });

        jTblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblFuncionarios);

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "M", "F" }));

        jLabel4.setText("Sexo:");

        jLabel5.setText("Nombres:");

        jTFNombres.setName("Nombres"); // NOI18N

        jLabel6.setText("Apellidos:");

        jTFApellidos.setName("Apellidos"); // NOI18N

        jLabel7.setText("Telefono:");

        try {
            jFFTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("Fecha Nac.:");

        jLabel9.setText("Estado Civil:");

        JCBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Dirección:");

        jTADireccion.setColumns(20);
        jTADireccion.setRows(5);
        jScrollPane2.setViewportView(jTADireccion);

        jBSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBSalir.setForeground(new java.awt.Color(255, 0, 0));
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 616, Short.MAX_VALUE)
                        .addComponent(jBRefrescar)
                        .addGap(48, 48, 48)
                        .addComponent(jBEliminar)
                        .addGap(65, 65, 65)
                        .addComponent(jBEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFApellidos)
                            .addComponent(JDChFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNombres))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JCBEstadoCivil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, 228, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jFFTelefono))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addGap(114, 114, 114)))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(JCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jTFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jFFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JDChFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBRefrescar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        if(Mensajes.mensajeConfirm("Salir del Sistema", "¿Seguro desea salir?")){
           this.dispose();
        }
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        if(guardar()){
            System.out.println("Guardado exitoso!");
            llenarTablaFuncionarios();
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblFuncionariosMouseClicked
        // TODO add your handling code here:
        if(jTblFuncionarios.getSelectedRow() != -1){
            jBEliminar.setEnabled(true);
            jBEditar.setEnabled(true);
        }
    }//GEN-LAST:event_jTblFuncionariosMouseClicked

    private void jBRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefrescarActionPerformed
        // TODO add your handling code here:
        limpiar();
        llenarTablaFuncionarios();
    }//GEN-LAST:event_jBRefrescarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:}
        if(Mensajes.mensajeConfirm("Eliminar", "¿Deseas Eliminar?")){
            eliminar();
            llenarTablaFuncionarios();
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        if(Mensajes.mensajeConfirm("Editar", "¿Deseas Editar?")){
            actualizar();
            llenarTablaFuncionarios();
            limpiar();
        }
    }//GEN-LAST:event_jBEditarActionPerformed


    private void completar(){
        jTblFuncionarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {


                JTable table = (JTable)evt.getSource();
                Point point = evt.getPoint();
                int row = table.rowAtPoint(point);
                if (evt.getClickCount() == 2  && table.getSelectedRow() != -1) {

                    jTFDocumento.setText(jTblFuncionarios.getValueAt(row, 1).toString());
                    jTFNombres.setText(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 2).toString());
                    jTFApellidos.setText(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 3).toString());
                    jTADireccion.setText(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 5).toString());
                    jFFTelefono.setText(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 6).toString());
                    JDChFechaNac.setDate(java.sql.Date.valueOf(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 7).toString()));
                    jCBTipoDocumento.setSelectedItem(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 8).toString());
                    JCBEstadoCivil.setSelectedItem(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 9).toString());
                    jCBSexo.setSelectedItem(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 4).toString());

                }
            }
        });
    }
    private void limpiar(){
        jTFDocumento.setText("");
        jTFNombres.setText("");
        jTFApellidos.setText("");
        jFFTelefono.setText("");
        jTADireccion.setText("");
        jCBTipoDocumento.setSelectedIndex(0);
        JCBEstadoCivil.setSelectedIndex(0);
        jCBSexo.setSelectedIndex(0);
        JDChFechaNac.setCalendar(null);
    }
    
    private void eliminar(){
        String documento = (String)jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 1);
        funcionarioCtrl.eliminar(documento);
    }
    
    private boolean guardar(){
        Funcionario funcionario = new Funcionario();
        TipodeIdentificacion tipoId = new TipodeIdentificacion(jCBTipoDocumento.getSelectedIndex() + 1);
        funcionario.setIdTipodeIdentificacion(tipoId);
        funcionario.setNumeroIdentificacion(jTFDocumento.getText().trim());
        funcionario.setNombre(jTFNombres.getText().trim());
        funcionario.setApellido(jTFApellidos.getText().trim());
        funcionario.setSexo(jCBSexo.getSelectedItem().toString());
        funcionario.setTelefono(jFFTelefono.getText());
        if(JDChFechaNac.getDate() != null){
            funcionario.setFechaNacimiento(JDChFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        }else{
            funcionario.setFechaNacimiento(LocalDate.now(ZoneId.systemDefault()));
        }
        EstadoCivil estadoCivil = new EstadoCivil(JCBEstadoCivil.getSelectedIndex() + 1);
        funcionario.setIdEstadoCivil(estadoCivil);
        funcionario.setDireccion(jTADireccion.getText().trim());
        int resultado = funcionarioCtrl.guardar(funcionario);
        limpiar();
        return resultado > 0;


    }

    private boolean actualizar(){
        Funcionario funcionario = new Funcionario();


        TipodeIdentificacion tipoId = new TipodeIdentificacion(jCBTipoDocumento.getSelectedIndex() + 1);
        funcionario.setId(Integer.parseInt(jTblFuncionarios.getValueAt(jTblFuncionarios.getSelectedRow(), 0).toString()));
        funcionario.setIdTipodeIdentificacion(tipoId);
        funcionario.setNumeroIdentificacion(jTFDocumento.getText().trim());
        funcionario.setNombre(jTFNombres.getText().trim());
        funcionario.setApellido(jTFApellidos.getText().trim());
        funcionario.setSexo(jCBSexo.getSelectedItem().toString());
        funcionario.setTelefono(jFFTelefono.getText());
        if(JDChFechaNac.getDate() != null){
            funcionario.setFechaNacimiento(JDChFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        }else{
            funcionario.setFechaNacimiento(LocalDate.now(ZoneId.systemDefault()));
        }
        EstadoCivil estadoCivil = new EstadoCivil(JCBEstadoCivil.getSelectedIndex() + 1);
        funcionario.setIdEstadoCivil(estadoCivil);
        funcionario.setDireccion(jTADireccion.getText().trim());
        int resultado = funcionarioCtrl.actualizar(funcionario);
        limpiar();
        return resultado > 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCBEstadoCivil;
    private com.toedter.calendar.JDateChooser JDChFechaNac;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBRefrescar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBSexo;
    private javax.swing.JComboBox<String> jCBTipoDocumento;
    private javax.swing.JFormattedTextField jFFTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADireccion;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFDocumento;
    private javax.swing.JTextField jTFNombres;
    private javax.swing.JTable jTblFuncionarios;
    // End of variables declaration//GEN-END:variables
}
